# This file generates the GitHub Actions matrix.
# See https://zmk.dev/docs/development/build-flash for details.
include:
  - board: nice_nano_v2
    shield: lily58_left
  - board: nice_nano_v2
    shield: lily58_right
  - board: nice_nano_v2
    shield: settings_reset
